name: support_for_better_livingspace
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.9.0   # For initializing Firebase
  cloud_firestore: ^5.0.0 # For Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/plumber.png
    - assets/cartender.png
    - assets/gardener.png
    - assets/electrician.png
    - assets/CartenderREKLAM.jpeg
    - assets/plumberREKLAM.jpeg
    - assets/electricianREKLAM.jpeg
